name: Backend - Build & Push

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev, homologation]

permissions:
  contents: read
  packages: write

concurrency:
  group: backend-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Gabrimeireles/reusable-workflows/.github/workflows/docker-build.yml@v1.3
    with:
      image_name: coguide-api
      dockerfile: dockerfile
      context: .
      node_version: '20'

